### ISSUE TITLE
Bug: Initial task addition after input parameter creates syntax error

### ISSUE THREAD

**Issue by bigmstone** [StackStorm/st2flow#123]
When creating a new workflow if you add an input parameter before adding the first task the syntax for the workflow is created incorrectly. The following is an example of the incorrect syntax that is created:

```
---
version: '2.0'

default.test:
  tasks:
  input:
    - test_param
    task1:
      action: test.echoer

```
