### ISSUE TITLE
Describe syntax for adding metadata with comments

### ISSUE THREAD

**Issue by DesignByOnyx** [StackStorm/st2flow#144]
This issue is a place to bikeshed about `# comment` parsing in the new st2flow editor. As of right now, the only meaningful comments in a workflow are used to describe the `x` and `y` coordinates for a task in the workflow editor:

```yaml
tasks:
  # [350, 250]
  task1: ...
```

Are there any other considerations we should make? For example, we could support arbitrary meta-data in the form of JSON:

```yaml
tasks:
  # [350, 250]
  # { "foo": "bar" }
  task1: ...
```
... or multiline

```yaml
tasks:
  # [350, 250]
  # { 
  #    "foo": "bar" 
  # }
  task1: ...
```

Please leave your thoughts in a comment.
