### ISSUE TITLE
[3.0dev] Error: "should NOT have additional properties..."

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2flow#189]
If I install the examples pack, then edit `examples.mistral-basic`, I see this error at the bottom of the canvas:

<img width="567" alt="image" src="https://user-images.githubusercontent.com/3607046/49486173-554c2500-f7f2-11e8-9e46-631505a12840.png">

I believe that this message is incorrect. The workflow definition looks like this:

```yaml
version: '2.0'

examples.mistral-basic:
    description: A basic workflow that runs an arbitrary linux command.
    type: direct
    input:
        - cmd
        - timeout
    output:
        stdout: <% $.stdout %>
    tasks:
        task1:
            action: core.local cmd=<% $.cmd %> timeout=<% $.timeout %>
            publish:
                stdout: <% task(task1).result.stdout %>
                stderr: <% task(task1).result.stderr %>
```

That looks like a valid configuration to me. I see the same pattern with other workflows - that same error message.
