### ISSUE TITLE
Comment before the task should be a part of this task, not last one.

### ISSUE THREAD

**Issue by enykeev** [StackStorm/st2flow#22]
So say, you have a workflow and you've added a nice comment before the task to explain what it does (as @m4dcoder did in https://github.com/StackStorm/st2incubator/blob/master/packs/st2ci/actions/workflows/mistral.yaml):

`````` yaml
...
            notify:
                action: slack.post_message
                input:
                    channel: '#thunderdome'
                    message: '```[MISTRAL-CI][<% $.mis_repo_base %>] STATUS: SUCCEEDED```'

            # Declare error handler(s) for the main workflow here.
            teardown_on_failure:
                workflow: teardown_infra
                input:
                    host: <% $.hosts.get(test) %>
                    clones: <% $.setup.clones %>
                on-complete:
                    - notify_on_failure
...
``````

Now you want to connect this task to the other one and this is what you end up with:

`````` yaml
...
            notify:
                action: slack.post_message
                input:
                    channel: '#thunderdome'
                    message: '```[MISTRAL-CI][<% $.mis_repo_base %>] STATUS: SUCCEEDED```'

            # Declare error handler(s) for the main workflow here.
                on-success:
                    - teardown_on_failure
            teardown_on_failure:
                workflow: teardown_infra
                input:
                    host: <% $.hosts.get(test) %>
                    clones: <% $.setup.clones %>
                on-complete:
                    - notify_on_failure
...
``````
