### ISSUE TITLE
Comments get stripped in transition blocks

### ISSUE THREAD

**Issue by enykeev** [StackStorm/st2flow#23]
By connecting two task together

``` yaml
...
            setup_st2:
                action: st2ci.setup_st2
                input:
                    host: <% $.host %>
                    repo: <% $.st2_repo %>
                    repo_branch: <% $.st2_repo_branch %>
                    repo_dir: <% $.st2_repo_dir %>
                    debug: <% $.debug %>
                publish:
                    st2_clone_path: <% $.setup_st2.clone_path %>
                on-error:
                    # Manually tear down mistral here because by the time setup_st2
                    # runs, the mistral infrastructure is already setup. Each setup
                    # task above automatically rollback on error unless debugging.
                    - teardown_mistral: <% not $.debug %>
...
```

becomes this

``` yaml
...
            setup_st2:
                action: st2ci.setup_st2
                input:
                    host: <% $.host %>
                    repo: <% $.st2_repo %>
                    repo_branch: <% $.st2_repo_branch %>
                    repo_dir: <% $.st2_repo_dir %>
                    debug: <% $.debug %>
                publish:
                    st2_clone_path: <% $.setup_st2.clone_path %>
                on-error:
                    - teardown_mistral
                    - compose_shas
...
```

Yeah, at the moment we also strip transition conditions, but that's another question.
