### ISSUE TITLE
Orquesta model: transition when property (possibly others) mishandled when only newlines

### ISSUE THREAD

**Issue by bmomberger-bitovi** [StackStorm/st2flow#259]
- Put just a newline into the when field for a transition.  The YAML becomes something similar to this:
```
    next:
      # #aad
      - do:
          - task2
        when: 
: 
        publish:
          - foo: <% result().bar %>

```
  - that mystery colon at the beginning of the line after "when:" shouldn't happen.
