### ISSUE TITLE
Task name should not allow spaces or newlines

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2flow#323]
st2flow lets me create a task name with newlines and spaces, resulting in oddities like this:

```yaml
version: 1.0
tasks:
  # [201, 155]
  foo
bar
fa:
    action: chatops.format_execution_result
```

^^ this was with one action on canvas, set name to `foo\nbar\nfa`
