### ISSUE TITLE
Mistral Transitions - no option for on-success/error/complete

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2flow#330]
Mistral lets us have `on-success`/`on-error`/`on-complete` conditions, as well as matching based upon variables.

e.g.:

```yaml
        t1:
            action: core.local
            input:
                cmd: "printf <% $.which %>"
            publish:
                path: <% task(t1).result.stdout %>
            on-success:
                - a: <% $.path = 'a' %>
                - b: <% $.path = 'b' %>
                - c: <% not $.path in list(a, b) %>
            on-error:
                - error_message
```

st2flow only lets us configure the expression, and puts everything under `on-complete`. 

Under the previous st2flow model, we would choose the on-success/error/complete condition by clicking the desired option when connecting tasks.

We probably need a drop-down for success/error/complete, and a box to set the optional conditional expression
