### ISSUE TITLE
Mistral workflows can't cope with snide comments

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2flow#331]
This workflow loads:

```yaml
version: '2.0'

examples.mistral-basic:
    description: A basic workflow that runs an arbitrary linux command.
    type: direct
    input:
        - cmd
        - timeout
    output:
        stdout: <% $.stdout %>
    tasks:
        task1:
            action: core.local cmd=<% $.cmd %> timeout=<% $.timeout %>
            publish:
                stdout: <% task(task1).result.stdout %>
                stderr: <% task(task1).result.stderr %>
```

But adding a comment like this:

```yaml
    tasks:
        # This is my first task
        task1:
```

results in a blank screen, with this error in the console:

```
Invariant Violation: "Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. "
    ba https://10.10.10.10/flow/js/main.js:1
    x https://10.10.10.10/flow/js/main.js:1
    qf https://10.10.10.10/flow/js/main.js:1
    enqueueSetState https://10.10.10.10/flow/js/main.js:1
    setState https://10.10.10.10/flow/js/main.js:1
    unsubscribe https://10.10.10.10/flow/js/main.js:1
    dispatch https://10.10.10.10/flow/js/main.js:1
    promiseMiddleware https://10.10.10.10/flow/js/main.js:1
    issueModelCommand https://10.10.10.10/flow/js/main.js:1
    Canvas https://10.10.10.10/flow/js/main.js:1
    Canvas https://10.10.10.10/flow/js/main.js:1
    Canvas https://10.10.10.10/flow/js/main.js:1
    componentDidUpdate https://10.10.10.10/flow/js/main.js:1
    Vh https://10.10.10.10/flow/js/main.js:1
    Zh https://10.10.10.10/flow/js/main.js:1
    Fi https://10.10.10.10/flow/js/main.js:1
    unstable_runWithPriority https://10.10.10.10/flow/js/main.js:1
    Fi https://10.10.10.10/flow/js/main.js:1
    Di https://10.10.10.10/flow/js/main.js:1
    Yh https://10.10.10.10/flow/js/main.js:1
    Xh https://10.10.10.10/flow/js/main.js:1
    qf https://10.10.10.10/flow/js/main.js:1
    enqueueSetState https://10.10.10.10/flow/js/main.js:1
    setState https://10.10.10.10/flow/js/main.js:1
    unsubscribe https://10.10.10.10/flow/js/main.js:1
    dispatch https://10.10.10.10/flow/js/main.js:1
    promiseMiddleware https://10.10.10.10/flow/js/main.js:1
main.js:1:1641828
    qh https://10.10.10.10/flow/js/main.js:1
    callback https://10.10.10.10/flow/js/main.js:1
    ih https://10.10.10.10/flow/js/main.js:1
    hh https://10.10.10.10/flow/js/main.js:1
    Vh https://10.10.10.10/flow/js/main.js:1
    Zh https://10.10.10.10/flow/js/main.js:1
    Fi https://10.10.10.10/flow/js/main.js:1
    unstable_runWithPriority https://10.10.10.10/flow/js/main.js:1
    Fi https://10.10.10.10/flow/js/main.js:1
    Di https://10.10.10.10/flow/js/main.js:1
    Yh https://10.10.10.10/flow/js/main.js:1
    Xh https://10.10.10.10/flow/js/main.js:1
    qf https://10.10.10.10/flow/js/main.js:1
    enqueueSetState https://10.10.10.10/flow/js/main.js:1
    setState https://10.10.10.10/flow/js/main.js:1
    unsubscribe https://10.10.10.10/flow/js/main.js:1
    dispatch https://10.10.10.10/flow/js/main.js:1
    promiseMiddleware https://10.10.10.10/flow/js/main.js:1
```
