### ISSUE TITLE
Mistral workflow fully qualified action name error

### ISSUE THREAD

**Issue by jinpingh** [StackStorm/st2flow#357]
st2 --version
st2 3.0.0, on Python 2.7.6

Created and saved a new mistral workflow with name `test_mistral_wf`. Execution failed on error message ` Name of the workflow must be the same as the fully qualified action name "examples.test_mistral_wf"`

```
/opt/stackstorm/packs/examples/actions/test_mistral_wf.meta.yaml
pack: examples
enabled: true
runner_type: mistral-v2
name: test_mistral_wf
entry_point: workflows/test_mistral_wf.yaml
```
```
/opt/stackstorm/packs/examples/actions/workflows/test_mistral_wf.yaml
version: '2.0'
main:
  tasks:
    # [246, 304]
    task1:
      action: core.echo
      input:
        message: hello
```
![mistral_wf](https://user-images.githubusercontent.com/31353550/56755782-26086700-6745-11e9-8826-ae9b57875ec6.PNG)
