### ISSUE TITLE
Using a templating string instead of a list causes the entire web UI to crash

### ISSUE THREAD

**Issue by miyoyo** [StackStorm/st2flow#386]
Currently, when passing something such as:

```yaml
  notify_user:
    action: msexchange.send_email
    input:
      log_level: DEBUG
      body: "<% ctx().email_body %>"
      subject: "<% ctx().subject %>"
      to_recipients: <% ctx().to_recipients %>
```

Where to_recipients expects a _list_, even if the YAQL query returns a list, react fails to render and the screen goes permanently white until a full page reload.

The error happens here:
https://github.com/StackStorm/st2flow/blob/d7490794f78fb3f720d16b685464e1ace93615be/modules/st2-auto-form/fields/array.js#L101

![image](https://user-images.githubusercontent.com/3525610/97591791-42ebbd80-1a00-11eb-844f-2016e2c040aa.png)

The exact error is
![image](https://user-images.githubusercontent.com/3525610/97591879-58f97e00-1a00-11eb-85b7-b9dadaa607b5.png)

From what I understand, the method just _does not expect_ that `v` could be a bad string.

A quick fix would be to do a type check before attempting to return a value.

```js
  toStateValue(v) {
    if (jsonCheck(v)) {
      return JSON.stringify(v);
    }

    if (isJinja(v)) {
      return v;
    }

    const { secret } = this.props.spec || {};
    if (secret && v && !Array.isArray(v)) {
      return v;
    }

    if(v == null) {
        return '';
    }

    if(!Array.isArray(v)) {
      // "Invalid Value"
    }

    return v.join(', ');
  }
```
